@echo OFF

SETLOCAL

set EPICS_APP=%~dp0
set EPICS_APP_ADL_DIR=%EPICS_APP%/xxxApp/op/adl

REM Go to the startup dir
cd %EPICS_APP%

REM Set env vars for modules in RELEASE file
for /f "delims=" %%i IN ('release.pl .') DO %%i

set EPICS_DISPLAY_PATH=%EPICS_APP_ADL_DIR%
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%ALIVE%/aliveApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%AREA_DETECTOR%/ADApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%AUTOSAVE%/asApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%BUSY%/busyApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%CALC%/calcApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%CAMAC%/camacApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%CAPUTRECORDER%/caputRecorderApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%DAC128V%/dac128VApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%DELAYGEN%/delaygenApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%DEVIOCSTATS%/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%DXP%/dxpApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%IP%/ipApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%IP330%/ip330App/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%IPUNIDIG%/ipUnidigApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%LOVE%/loveApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%MCA%/mcaApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%MOTOR%/motorApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%OPTICS%/opticsApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%QUADEM%/quadEMApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%SSCAN%/sscanApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%STD%/stdApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%VME%/vmeApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%ASYN%/medm
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%VAC%/vacApp/op/adl
set EPICS_DISPLAY_PATH=%EPICS_DISPLAY_PATH%;%SOFTGLUE%/softGlueApp/op/adl

REM Add medm to the PATH
REM set PATH=%PATH%;C:\Program Files\EPICS Windows Tools

echo %EPICS_DISPLAY_PATH%

REM Launch medm
start medm -x -macro "P=xxx:" xxx.adl

ENDLOCAL
