TOP = ../..
include $(TOP)/configure/CONFIG
#!ARCH = windows-x64
#!ARCH = windows-x64-debug
ARCH = windows-x64-static
#!ARCH = win32-x86
#!ARCH = win32-x86-debug
#!ARCH = win32-x86-static
TARGETS = envPaths dllPath.bat
include $(TOP)/configure/RULES.ioc
