TOP = ../..
include $(TOP)/configure/CONFIG

ARCH = vxWorks-ppc32
#!ARCH = vxWorks-ppc32-debug
#!ARCH = vxWorks-ppc32sf
#!ARCH = vxWorks-ppc32sf-debug

TARGETS = cdCommands

include $(TOP)/configure/RULES.ioc
